/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/WZ52Ero2bgJ
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Rubik } from 'next/font/google'
import { Chivo } from 'next/font/google'

rubik({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Select, SelectTrigger } from "@/components/ui/select";
import { SelectContent, SelectItem, SelectValue } from "@radix-ui/react-select";
import Head from "../../components/component/head";
// import { Html } from "next/document";
import SVGProps from  "../../public/assets/Rightarrow.svg"
import { useState, useEffect } from "react"
import { MdOutlineArrowRight } from "react-icons/md";
import { BsArrowUpCircleFill } from "react-icons/bs";

function Docs() {
  const [showScrollToTopButton, setShowScrollToTopButton] = useState(false)
  useEffect(() => {
    const handleScroll = () => {
      if (window.pageYOffset > 300) {
        setShowScrollToTopButton(true)
      } else {
        setShowScrollToTopButton(false)
      }
    }
    window.addEventListener("scroll", handleScroll)
    return () => window.removeEventListener("scroll", handleScroll)
  }, [])
  const scrollToTop = () => {
    window.scrollTo({
      top: 0,
      behavior: "smooth",
    })
  }
  return (
    <div className="flex min-h-screen w-full flex-col bg-background">
      <Head />
      <div className="flex flex-1">
        <aside className="hidden w-60 shrink-0 border-r bg-background p-6 md:block">
          <nav className="space-y-2 overflow-y-auto">
          <h3 className="text-xl underline font-bold">Navigation</h3>
            <Link 
              href="#Introduction"
              className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium hover:bg-muted"
              prefetch={true}
            >
              <MdOutlineArrowRight />
              Introduction
            </Link>
            <Link
              href="#Features"
              className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium hover:bg-muted"
              prefetch={true}
            >
              <MdOutlineArrowRight />
              Features
            </Link>
            <Link
              href="#Uniqueness and Innovations"
              className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium hover:bg-muted"
              prefetch={true}
            >
              <MdOutlineArrowRight />
              Uniqueness and Innovations
            </Link>
            <Link
              href="#Technology stack"
              className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium hover:bg-muted"
              prefetch={true}
            >
              <MdOutlineArrowRight />
              Technology stack
            </Link>
            <Link
              href="#Potential benefits"
              className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium hover:bg-muted"
              prefetch={true}
            >
              <MdOutlineArrowRight />
              Potential benefits
            </Link>
            <Link
              href="#Impact of SCMS"
              className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium hover:bg-muted"
              prefetch={true}
            >
              <MdOutlineArrowRight />
              Impact of SCMS
            </Link>
            <Link
              href="#Long term impact"
              className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium hover:bg-muted"
              prefetch={true}
            >
              <MdOutlineArrowRight />
              Long term impact
            </Link>
            <Link
              href="#Conclusion"
              className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium hover:bg-muted"
              prefetch={true}
            >
              <MdOutlineArrowRight />
              Conclusion
            </Link>
          </nav>
        </aside>
        <main className="flex-1 p-6 md:p-10">
          <div id="Introduction" className="space-y-6">
            <h1 className="text-4xl font-bold"> 1. Introduction</h1>
            <p>
              The Smart Classroom Management Software (SCMS) leverages existing
              CCTV infrastructure combined with advanced machine learning (ML)
              models and IoT technologies to enhance classroom management,
              improve student engagement, and ensure safety. It offers real-time
              insights into student behavior, teacher performance, and overall
              classroom dynamics while providing tools for early intervention
              and resource optimization. The SCMS integrates various features
              like face detection, gaze tracking, emotional distress detection,
              and object detection to ensure a conducive learning environment.
            </p>
            <p>
              The SCMS integrates various features like face detection, gaze
              tracking, emotional distress detection, and object detection to
              ensure a conducive learning environment.
            </p>
          </div>
          <div id="Features" className="space-y-6 pt-6">
            <h2 className="text-4xl font-bold">2. Features</h2>

            <h4 className="font-bold text-xl ">2.1 Attendance Automation</h4>
            <ul>
              <li>
                • Automatically tracks attendance using facial recognition.
              </li>
              <li>
                • Real-time attendance reports accessible by teachers and
                administrators.
              </li>
              <li>
                • Reduces manual tracking of attendance, ensuring accuracy and
                saving time.
              </li>
            </ul>

            <h4 className="font-bold text-xl">2.2 Gaze Tracking</h4>
            <ul>
              <li>
                • Tracks where students are looking to monitor attentiveness.
              </li>
              <li>
                • Provides real-time feedback to teachers about student
                engagement.
              </li>
              <li>
                • Helps assess focus during lectures and interactive sessions.
              </li>
            </ul>
            <h4 className="font-bold text-xl">
              2.3 Facial Expression and Mood Detection
            </h4>
            <ul>
              <li>
                • Analyzes facial expressions to gauge students emotional
                states (e.g., boredom, confusion, interest).{" "}
              </li>
              <li>
                • Provides insight into individual or collective student moods
                throughout lessons.{" "}
              </li>
              <li>
                • Data can be used to adapt teaching methods to student
                engagement levels.{" "}
              </li>
            </ul>
            <h4 className="font-bold text-xl">
              {" "}
              2.4 Activity Detection (Behavior Monitoring)
            </h4>
            <ul>
              <li>
                • Detects disruptive behaviors such as fighting, smoking, or
                other inappropriate activities using ML-based action recognition
                models.
              </li>
              <li>
                • Real-time alerts for immediate intervention when disruptive
                behavior is detected.{" "}
              </li>
              <li>
                • Helps maintain discipline and a productive classroom
                atmosphere.{" "}
              </li>
            </ul>
            <h4 className="font-bold text-xl">
              {" "}
              2.5 Unwanted Object Detection
            </h4>
            <ul>
              <li>
                • Detects unwanted items in the classroom (e.g., knives,
                cigarettes, phones) using object detection models like YOLOv8 or
                SSD.
              </li>
              <li>
                • Sends real-time alerts when prohibited items are detected.
              </li>
              <li>
                • Enhances security and ensures adherence to classroom rules.
              </li>
            </ul>
            <h4 className="font-bold text-xl">
              2.6 Emotional Distress Detection
            </h4>
            <ul>
              <li>
                • Analyzes data patterns over time to detect signs of emotional
                distress among students.{" "}
              </li>
              <li>
                • Alerts teachers and administrators about students who may need
                psychological or emotional support.{" "}
              </li>
              <li>• A proactive approach to managing student well-being. </li>
            </ul>
            <h4 className="font-bold text-xl">
              2.7 Safety and Security Alerts
            </h4>
            <ul>
              <li>
                • Detects security concerns such as fire, unauthorized access,
                or dangerous objects.{" "}
              </li>
              <li>
                • Real-time notifications are sent to relevant authorities or
                personnel for immediate action.{" "}
              </li>
              <li>
                • Ensures the safety of students, staff, and school property.{" "}
              </li>
            </ul>

            <h4 className="font-bold text-xl">2.8 Resource Management</h4>
            <ul>
              <li>
                • Tracks and manages classroom resources (e.g., projectors,
                computers, smartboards) using IoT technology.{" "}
              </li>
              <li>
                • Automates the scheduling and maintenance of classroom
                equipment, reducing downtime.{" "}
              </li>
              <li>
                • Centralized dashboard for monitoring resource usage and
                optimizing efficiency.{" "}
              </li>
            </ul>

            <h4 className="font-bold text-xl">
              {" "}
              2.9 Interactive Learning Tools
            </h4>
            <ul>
              <li>
                • Integrates with smartboards and interactive displays to
                enhance teaching and learning experiences.{" "}
              </li>
              <li>
                • Provides real-time feedback on how students interact with
                learning materials.
              </li>
              <li>
                •Allows teachers to adjust their teaching approach based on
                student engagement.{" "}
              </li>
            </ul>

            <h4 className="font-bold text-xl">
              2.10 Environmental Monitoring and Control
            </h4>
            <ul>
              <li>
                • Monitors classroom environmental factors such as temperature,
                lighting, and air quality using IoT sensors.
              </li>
              <li>
                • Automatically adjusts HVAC systems and lighting for optimal
                learning conditions.
              </li>
              <li>
                • Ensures a comfortable and conducive environment for both
                students and teachers.
              </li>
            </ul>

            <h4 className="font-bold text-xl"> 2.11 Energy Efficiency</h4>
            <ul>
              <li>
                • Uses IoT-enabled smart plugs and sensors to monitor and
                control energy consumption in the classroom.{" "}
              </li>
              <li>
                • Automates energy-saving actions (e.g., turning off lights,
                equipment) when the classroom is unoccupied.
              </li>
              <li>
                • Helps reduce operational costs and improve energy efficiency.
              </li>
            </ul>

            <h4 className="font-bold text-xl">
              2.12 Real-Time Data Collection and Analytic
            </h4>
            <ul>
              <li>
                • Collects data on student behavior, engagement, attendance, and
                resource usage in real-time.{" "}
              </li>
              <li>
                • Provides actionable insights for teachers and administrators
                through visual dashboards and reports{" "}
              </li>
              <li>
                • Helps optimize classroom management and improve student
                outcomes.
              </li>
            </ul>

            <h4 className="font-bold text-xl">
              {" "}
              2.13 Real-Time Alerts and Notifications
            </h4>
            <ul>
              <li>
                • Sends real-time alerts for disruptive behaviors, security
                issues, and safety threats.{" "}
              </li>
              <li>
                • Alerts can be delivered via SMS, email, or mobile app
                notifications to relevant staff members.{" "}
              </li>
              <li>
                • Ensures timely interventions for maintaining order and safety.{" "}
              </li>
            </ul>

            <h4 className="font-bold text-xl">
              2.14 Cloud-Based Storage and Processing
            </h4>
            <ul>
              <li>
                • Uses cloud platforms (e.g., AWS, Azure, Google Cloud) for
                scalable and secure data storage.{" "}
              </li>
              <li>
                • Handles large volumes of video data and real-time analytics in
                the cloud.
              </li>
              <li>
                • Enables remote access to reports and data for administrators
                and teachers.
              </li>
            </ul>
            <h4 className="font-bold text-xl">
              2.15 Teacher Performance Analytics
            </h4>
            <ul>
              <li>
                • Generates reports to assess teacher performance based on
                student engagement metrics and classroom dynamics.{" "}
              </li>
              <li>
                • Uses KPIs like student attentiveness, behavioral trends, and
                learning outcomes to evaluate teaching effectiveness.{" "}
              </li>
              <li>
                • Provides insights for continuous improvement and personalized
                professional development.
              </li>
            </ul>
          </div>
          <div id="Uniqueness and Innovations" className="space-y-6 pt-6">
            <h2 className="text-4xl font-bold ">
              3. Uniqueness and Innovations
            </h2>

            <h4 className="font-bold text-xl">
              {" "}
              3.1 Integration of Existing CCTV Infrastructure
            </h4>
            <ul>
              <li>
                • Uses existing CCTV cameras to minimize additional hardware
                costs.
              </li>
              <li>
                • Provides a cost-effective and scalable solution by leveraging
                already available resources.
              </li>
            </ul>
            <h4 className="font-bold text-xl">
              3.2 Real-Time, Multi-Faceted Monitoring
            </h4>
            <ul>
              <li>
                • Integrates face detection, gaze tracking, emotional analysis,
                and behavior recognition in real-time.
              </li>
              <li>
                • Monitors both educational activities and classroom security,
                offering a holistic solution.
              </li>
            </ul>
            <h4 className="font-bold text-xl">
              3.3 Emotional Distress Detection
            </h4>
            <ul>
              <li>
                • Innovative use of student data patterns to detect emotional
                distress and mental health issues.
              </li>
              <li>
                • Allows proactive intervention by teachers and school
                counselors.
              </li>
            </ul>
            <h4 className="font-bold text-xl">
              {" "}
              3.4 Machine Learning-Powered Insights
            </h4>
            <ul>
              <li>
                • Utilizes ML models for object detection and behavior analysis,
                making the system adaptive and improving accuracy over time.
              </li>
              <li>
                • Continuous learning from classroom data enables better
                predictions and faster responses.
              </li>
            </ul>
            <h4 className="font-bold text-xl">
              3.5 Teacher Performance Analytics
            </h4>
            <ul>
              <li>
                • Provides data-driven insights into teacher performance based
                on student engagement metrics.
              </li>
              <li>
                • Offers personalized recommendations for teachers based on
                classroom dynamics and student behavior.
              </li>
            </ul>
            <h4 className="font-bold text-xl">
              3.6 Comprehensive Security Monitoring
            </h4>
            <ul>
              <li>
                • Integrates safety features (e.g., fire detection, unauthorized
                access) into the educational environment.
              </li>
              <li>
                • Offers a dual-purpose solution for managing both educational
                and safety concerns.
              </li>
            </ul>
          </div>
          <div id="Technology stack" className="space-y-6 pt-6">
            <h2 className="text-4xl font-bold">4. Technology Stack</h2>

            <h4 className="font-bold text-xl">4.1 Machine Learning Models</h4>
            <ul>
              <li>
                • YOLOv8 / SSD for object detection (knives, cigarettes,
                phones).{" "}
              </li>
              <li>
                • I3D / Two-Stream CNN for activity detection (fighting,
                smoking).{" "}
              </li>
              <li>
                • OpenCV / Gaze360 for gaze tracking and attentiveness analysis.{" "}
              </li>
              <li>
                • Facial expression analysis for mood detection and emotional
                distress tracking.{" "}
              </li>
            </ul>

            <h4 className="font-bold text-xl">4.2 IoT Integration</h4>
            <ul>
              <li>
                • Sensors for monitoring temperature, lighting, CO2 levels, etc.{" "}
              </li>
              <li>
                • Smart devices (e.g., smartboards, projectors) for resource
                management and automation.{" "}
              </li>
              <li>
                • Wearables for tracking student physical health and activity
                levels.{" "}
              </li>
            </ul>

            <h4 className="font-bold text-xl">
              4.3 Data Processing and Storage{" "}
            </h4>
            <ul>
              <li>
                • AWS IoT Core / Azure IoT Hub / Google Cloud IoT for managing
                IoT devices and real-time data processing.{" "}
              </li>
              <li>
                • Cloud platforms (AWS, Azure, Google Cloud) for scalable and
                secure data storage and analytics.{" "}
              </li>
            </ul>
            <h4 className="font-bold text-xl">4.4 Communication and Alerts</h4>
            <ul>
              <li>
                • Twilio or Firebase Cloud Messaging for real-time alerts and
                notifications.{" "}
              </li>
              <li>
                • Web-based dashboards for real-time data visualization and
                reporting.{" "}
              </li>
            </ul>
          </div>
          <div id="Potential benefits" className="space-y-6 pt-6">
            <h2 className="text-4xl font-bold"> 4. Potential Benifits</h2>

            <h4 className="font-bold text-xl">
              5.1 Enhanced Classroom Efficiency
            </h4>
            <ul>
              <li>
                • Automated Attendance Tracking: By utilizing facial recognition
                technology, the system can automatically track student
                attendance, reducing administrative tasks for teachers and
                ensuring accurate attendance records.
              </li>
              <li>
                • Real-Time Monitoring and Alerts: Teachers can receive
                real-time notifications about behavioral issues or security
                concerns, allowing for quick intervention to maintain order and
                safety in the classroom.
              </li>
            </ul>
            <h4 className="font-bold text-xl">
              5.2 Improved Student Engagement and Performance{" "}
            </h4>
            <ul>
              <li>
                • Behavioral and Emotional Analysis: The system can detect signs
                of disengagement, distress, or disruptive behavior. Teachers can
                use this information to adapt their teaching methods to better
                engage students.
              </li>
              <li>
                • Personalized Learning Insights: By tracking gaze patterns,
                attention levels, and emotional states, teachers can understand
                which teaching methods resonate best with students, enabling
                more personalized learning experiences.
              </li>
            </ul>
            <h4 className="font-bold text-xl">
              5.3 Increased Safety and Security{" "}
            </h4>
            <ul>
              <li>
                • Object Detection: Detecting unauthorized items such as
                weapons, cigarettes, or phones ensures that potential security
                threats are immediately flagged, helping to prevent dangerous
                situations.
              </li>
              <li>
                • IoT Integration for Resource and Environment Management : By
                automating environmental controls (e.g., lighting, temperature),
                the system can create optimal learning environments, reduce
                energy waste, and manage classroom resources more effectively.
              </li>
            </ul>
            <h4 className="font-bold text-xl">
              5.4 Streamlined Resource Management{" "}
            </h4>
            <ul>
              <li>
                • IoT Integration for Equipment : The system can monitor and
                automate classroom resources, such as projectors, computers, and
                lighting, reducing the workload on staff and ensuring that
                equipment is used efficiently.
              </li>
            </ul>

            <h4 className="font-bold text-xl">
              5.5 Data-Driven Decision Making{" "}
            </h4>
            <ul>
              <li>
                • Comprehensive Reporting : The system provides detailed reports
                on student engagement, behavioral patterns, and emotional
                states. Administrators and teachers can use this data to make
                informed decisions about resource allocation, teaching methods,
                and classroom policies.
              </li>
              <li>
                • Improved Teacher Performance : Real-time feedback on student
                engagement allows teachers to continuously improve their
                teaching styles based on data-driven insights.
              </li>
            </ul>
            <h4 className="font-bold text-xl">5.6 Parental Involvement </h4>
            <ul>
              <li>
                • Alerts and Communication : Parents can receive timely updates
                about their child&apos;s behavior, attendance, and even emotional
                well-being, encouraging a stronger home-school connection.
              </li>
            </ul>
          </div>
          <div id="Impact of SCMS" className="space-y-6 pt-6">
            <h2 className="text-4xl font-bold">6. Impact f SCMS</h2>

            <h4 className="font-bold text-xl">
              6.1 Positive Learning Environment
            </h4>
            <ul>
              <li>
                • The system can detect and prevent negative behaviors such as
                fighting or bullying, creating a safer and more supportive
                environment that fosters positive student interactions and
                learning.{" "}
              </li>
            </ul>
            <h4 className="font-bold text-xl">
              6.2 Mental Health and Well-Being
            </h4>
            <ul>
              <li>
                • By monitoring emotional states, SCMS can help identify
                students who are emotionally distressed, providing an
                opportunity for early intervention by counselors, improving
                student well-being and overall mental health.{" "}
              </li>
            </ul>
            <h4 className="font-bold text-xl">6.3 Reduced Teacher Burnout</h4>
            <ul>
              <li>
                • Automating administrative tasks such as attendance tracking,
                resource management, and even behavior monitoring can
                significantly reduce the workload on teachers, allowing them to
                focus more on teaching and student engagement.{" "}
              </li>
            </ul>
            <h4 className="font-bold text-xl">6.4 Safer School Environment</h4>
            <ul>
              <li>
                • With the integration of object detection and real-time alerts,
                the SCMS improves school safety by detecting security threats
                early, helping school staff and authorities to respond
                proactively.{" "}
              </li>
            </ul>

            <h4 className="font-bold text-xl">6.5 Efficient Resource Usage</h4>
            <ul>
              <li>
                • By integrating IoT technology to monitor and control classroom
                resources, the system promotes sustainable energy usage, which
                could lead to lower operational costs for educational
                institutions.{" "}
              </li>
            </ul>
            <h4 className="font-bold text-xl">
              6.6 Enhanced School Reputation:
            </h4>
            <ul>
              <li>
                • Schools that adopt advanced classroom management technologies
                may gain a reputation for being at the forefront of educational
                innovation, attracting more students and parents who prioritize
                safety and modern learning environments.{" "}
              </li>
            </ul>
          </div>
          <div id="Long term impact" className="space-y-6 pt-6">
            <h2 className="text-3xl font-bold">7. Long term impact</h2>

            <h4 className="font-bold text-xl"></h4>
            <ul>
              <li>
                • Cultural Shift in Education : Over time, schools that
                integrate such technology could see a cultural shift towards a
                more data-driven and adaptive educational approach, where
                decisions are based on student engagement metrics and emotional
                well-being, rather than solely on test scores.{" "}
              </li>
            </ul>
          </div>
          <div id="Conclusion" className="space-y-6 pt-6">
            <h2 className="text-3xl font-bold">8. Conclusion</h2>

            <h4 className="font-bold text-xl"></h4>

            <ul>
              <li>
                • The Smart Classroom Management Software (SCMS) represents a
                revolutionary approach to classroom management and student
                engagement by integrating advanced machine learning, IoT, and
                real-time video analytics. The system&apos;s ability to detect
                emotional distress, monitor teacher performance, and ensure
                classroom safety makes it a comprehensive tool for modern
                educational settings. Its cost-effectiveness, scalability, and
                ability to provide personalized insights for both students and
                teachers make it an innovative solution that caters to the
                dynamic needs of today&apos;s classrooms.{" "}
              </li>
            </ul>
          </div>
        </main>
      </div>
      {showScrollToTopButton && (
        <button
          className="fixed bottom-6 right-6 z-50 rounded-lg bg-primary p-3 text-primary-foreground shadow-lg transition-all hover:bg-primary/80 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
          onClick={scrollToTop}
        >
          <BsArrowUpCircleFill className="w-10 h-10" />
          <span className="sr-only">Scroll to top</span>
        </button>
      )}
    </div>
  );
}

export default Docs;
