/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/E1lkOcqBxUf
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { JSX, SVGProps } from "react"

function foot() {
  return (
    <footer className="bg-muted md:py-8 bg-[#0B2543] text-white grid grid-cols-3 px-4 py-3">
      <div className="container flex flex-col items-start justify-start gap-4 md:flex-row">
      <div className="flex items-start space-x-4">
          <img
            src="https://it.delhi.gov.in/sites/default/files/logo/emblem-dark-logo_5.png"
            alt="Logo"
            className="h-12"
            width="28"
            height="25"
            style={{ aspectRatio: "50/50", objectFit: "cover" }}
          />
          <div>
            <h1 className="text-xl font-bold">Smart Classroom Management System</h1>
            <p className="text-sm">Government of NCT of Delhi</p>
          </div>
        </div>
        {/* <div className="flex-1 flex justify-start items-center mt-16 pl-10">
          <p className="text-sm text-muted-foreground">
            Made by{" "}
            <Link href="#" className="font-medium hover:underline" prefetch={false}>
              Team X
            </Link>
          </p>
        </div> */}
        </div>
        {/* this is head bar */}
        <div className="flex flex-row ml-auto gap-8">
        <div className="flex flex-row gap-8">
        <nav className="flex flex-col gap-4 text-sm">
          <h3 className="font-bold underline ">Quick Links</h3>
          <Link href="/docs" className="hover:underline" prefetch={false}>
            Documents
          </Link>
          <Link href="/demo" className="hover:underline" prefetch={false}>
            Demo
          </Link>
          <Link href="/media " className="hover:underline" prefetch={false}>
            Media
          </Link>
          <Link href="/faq" className="hover:underline" prefetch={false}>
            Faq
          </Link>
          <Link href="/contact" className="hover:underline" prefetch={false}>
            Contact
          </Link>
        </nav>
        </div>
        </div>
        <div className="flex flex-row ml-auto gap-8">
        <div className="flex flex-row gap-8">
        <nav className="flex flex-col gap-4 text-sm pr-10">
          <h3 className="font-bold underline ">Quick Links</h3>
          <Link href="#" className="hover:underline" prefetch={false}>
            Youtube link
          </Link>
          <Link href="/about" className="hover:underline" prefetch={false}>
            About
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            Instagram
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            Facebook
          </Link>
        </nav>
        </div>
        </div>
    </footer>
  )
}

function SmileIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M8 14s1.5 2 4 2 4-2 4-2" />
      <line x1="9" x2="9.01" y1="9" y2="9" />
      <line x1="15" x2="15.01" y1="9" y2="9" />
    </svg>
  )
}

export default foot;
