/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/E82EZUse5DM
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Chivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

import Link from "next/link"
import { JSX, SVGProps } from "react"
import { Button } from "@/components/ui/button"
import { Select, SelectTrigger } from "@/components/ui/select"
import { SelectContent, SelectItem, SelectValue } from "@radix-ui/react-select"
import Head from '../../components/component/head'

function media() {
  return (
  <div>
    <Head />
   
    <div className="flex flex-col items-center justify-center w-full h-full">
      <div className="container max-w-4xl px-4 py-12 space-y-6">
        <div className="text-center">
          <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">
            Check out Our Latest Video
          </h1>
          
        </div>
        <div className="flex flex-col md:flex-row items-center justify-center w-full h-full">
      <div className="container max-w-4xl px-4 py-12 space-y-6 md:pr-12 md:w-1/2">
        <div className="relative w-full aspect-video rounded-lg overflow-hidden">
          <iframe
            src="https://www.youtube.com/embed/iLWAdLnvw0E?si=e7YoMdsaq8reRDRa"
            title="YouTube video player"
            frameBorder="0"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
            allowFullScreen
            className="w-full h-full"
          />
        </div>
      </div>
      <div className="container max-w-4xl px-4 py-12 space-y-6 md:w-1/2">
        <div className="text-center md:text-left">
          <h3 className="font-bold tracking-tight sm:text-2xl">
            Demo of our face tracking feature
          </h3>
          <p className="mt-4 text-muted-foreground md:text-xl">
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Perferendis qui voluptas dolore assumenda voluptate? Consectetur consequuntur natus repellat sequi cumque fuga, ducimus nesciunt cupiditate iusto iste porro labore dolor beatae?
          </p>
        </div>
      </div>
    </div>
      </div>
    </div>
  </div>
  )
}

export default media;