/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/fXRitO8hKBd
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "@/components/ui/accordion"
import { JSX, SVGProps } from "react"
import Head from '../../components/component/head'

function faq() {
  return (
    <div>
      <Head />

    <section className="py-12 md:py-16 lg:py-20">
      
      <div className="container px-4 md:px-6">
        <div className="max-w-3xl mx-auto">
          <h2 className="text-3xl font-bold tracking-tight mb-8 md:text-4xl">Frequently Asked Questions</h2>
          <Accordion type="single" collapsible className="space-y-4">
            <AccordionItem value="question-1">
              <AccordionTrigger className="flex items-center justify-between bg-background rounded-md px-4 py-3 text-lg font-medium hover:bg-muted">
                <span>1. What is SCMS?</span>
              </AccordionTrigger>
              <AccordionContent className="bg-background rounded-md px-4 py-3 text-muted-foreground">
              The Smart Classroom Management Software (SCMS) is a technology-driven solution that leverages AI, machine learning, and IoT to automate attendance, monitor student behavior, and optimize classroom resource management. It provides real-time insights into student engagement, emotional well-being, and safety.
              </AccordionContent>
            </AccordionItem>
            <AccordionItem value="question-2">
              <AccordionTrigger className="flex items-center justify-between bg-background rounded-md px-4 py-3 text-lg font-medium hover:bg-muted">
                <span>2. How does SCMS track student attendance?</span>
              </AccordionTrigger>
              <AccordionContent className="bg-background rounded-md px-4 py-3 text-muted-foreground">
              SCMS uses facial recognition technology to automatically identify and log student attendance in real-time. This eliminates the need for manual roll calls and ensures accuracy.
              </AccordionContent>
            </AccordionItem>
            <AccordionItem value="question-3">
              <AccordionTrigger className="flex items-center justify-between bg-background rounded-md px-4 py-3 text-lg font-medium hover:bg-muted">
                <span>How does SCMS detect student behavior or mood?</span>
              </AccordionTrigger>
              <AccordionContent className="bg-background rounded-md px-4 py-3 text-muted-foreground">
              SCMS integrates machine learning algorithms to detect facial expressions and body movements. It monitors students for signs of disruptive behaviors (e.g., fighting, sleeping) and analyzes facial cues to understand their emotional states, such as stress or disengagement.
              </AccordionContent>
            </AccordionItem>
            <AccordionItem value="question-4">
              <AccordionTrigger className="flex items-center justify-between bg-background rounded-md px-4 py-3 text-lg font-medium hover:bg-muted">
                <span>4. What role does IoT play in SCMS?</span>
              </AccordionTrigger>
              <AccordionContent className="bg-background rounded-md px-4 py-3 text-muted-foreground">
                We accept all major credit cards, PayPal, and Apple Pay. Your payment information is securely encrypted
                and protected.
              </AccordionContent>
            </AccordionItem>
            <AccordionItem value="question-5">
              <AccordionTrigger className="flex items-center justify-between bg-background rounded-md px-4 py-3 text-lg font-medium hover:bg-muted">
                <span>5. How does SCMS enhance classroom safety?</span>
              </AccordionTrigger>
              <AccordionContent className="bg-background rounded-md px-4 py-3 text-muted-foreground">
              SCMS employs object detection models like YOLOv8 to identify prohibited items (e.g., knives, phones) in the classroom. The system sends real-time alerts to teachers and administrators, ensuring immediate action can be taken.
              </AccordionContent>
            </AccordionItem>
            <AccordionItem value="question-6">
              <AccordionTrigger className="flex items-center justify-between bg-background rounded-md px-4 py-3 text-lg font-medium hover:bg-muted">
                <span>6. Can parents access SCMS data?</span>
              </AccordionTrigger>
              <AccordionContent className="bg-background rounded-md px-4 py-3 text-muted-foreground">
              While the primary users are teachers and administrators, SCMS can be configured to send alerts or reports to parents, keeping them informed about their child&apos;s behavior, attendance, and emotional well-being.
              </AccordionContent>
            </AccordionItem>
            <AccordionItem value="question-7">
              <AccordionTrigger className="flex items-center justify-between bg-background rounded-md px-4 py-3 text-lg font-medium hover:bg-muted">
                <span>7. Is the system scalable?</span>
              </AccordionTrigger>
              <AccordionContent className="bg-background rounded-md px-4 py-3 text-muted-foreground">
              Yes, SCMS is highly scalable. It can be implemented in individual classrooms or across entire school districts. Cloud-based storage and IoT integration allow for seamless scaling based on the institution’s needs.
              </AccordionContent>
            </AccordionItem>
            <AccordionItem value="question-8">
              <AccordionTrigger className="flex items-center justify-between bg-background rounded-md px-4 py-3 text-lg font-medium hover:bg-muted">
                <span>8. What are the privacy implications of using SCMS?</span>
              </AccordionTrigger>
              <AccordionContent className="bg-background rounded-md px-4 py-3 text-muted-foreground">
              SCMS adheres to strict privacy and data protection protocols. All data is encrypted, and access is restricted to authorized personnel. Additionally, schools can configure data retention policies to meet privacy regulations such as GDPR or COPPA.
              </AccordionContent>
            </AccordionItem>
            <AccordionItem value="question-9">
              <AccordionTrigger className="flex items-center justify-between bg-background rounded-md px-4 py-3 text-lg font-medium hover:bg-muted">
                <span>9. How does SCMS integrate with other classroom systems?</span>
              </AccordionTrigger>
              <AccordionContent className="bg-background rounded-md px-4 py-3 text-muted-foreground">
              SCMS can be integrated with existing Learning Management Systems (LMS), digital gradebooks, and school communication platforms, ensuring a seamless experience for educators and administrators.
              </AccordionContent>
            </AccordionItem>
            <AccordionItem value="question-10">
              <AccordionTrigger className="flex items-center justify-between bg-background rounded-md px-4 py-3 text-lg font-medium hover:bg-muted">
                <span>10. How is SCMS different from other classroom management systems?</span>
              </AccordionTrigger>
              <AccordionContent className="bg-background rounded-md px-4 py-3 text-muted-foreground">
              While other systems focus on attendance tracking or digital learning, SCMS offers a more comprehensive solution by combining behavior detection, emotional analysis, and resource management with real-time data analytics, making it a holistic approach to classroom management.
              </AccordionContent>
            </AccordionItem>
            <AccordionItem value="question-11">
              <AccordionTrigger className="flex items-center justify-between bg-background rounded-md px-4 py-3 text-lg font-medium hover:bg-muted">
                <span>11. What technologies are used in SCMS?</span>
              </AccordionTrigger>
              <AccordionContent className="bg-background rounded-md px-4 py-3 text-muted-foreground">
              SCMS uses a combination of technologies, including OpenCV for video processing, AWS Rekognition for facial and mood detection, YOLOv8 for object detection, and Raspberry Pi/Arduino for IoT integration, all backed by databases like PostgreSQL and MongoDB
              </AccordionContent>
            </AccordionItem>
            <AccordionItem value="question-12">
              <AccordionTrigger className="flex items-center justify-between bg-background rounded-md px-4 py-3 text-lg font-medium hover:bg-muted">
                <span>12. Can SCMS work in remote learning environments?</span>
              </AccordionTrigger>
              <AccordionContent className="bg-background rounded-md px-4 py-3 text-muted-foreground">
              While SCMS is primarily designed for physical classrooms, many features like attendance tracking and engagement monitoring can be adapted to support hybrid and remote learning models using video conferencing tools.
              </AccordionContent>
            </AccordionItem>
            <AccordionItem value="question-13">
              <AccordionTrigger className="flex items-center justify-between bg-background rounded-md px-4 py-3 text-lg font-medium hover:bg-muted">
                <span>13. How does SCMS help teachers?</span>
              </AccordionTrigger>
              <AccordionContent className="bg-background rounded-md px-4 py-3 text-muted-foreground">
              SCMS automates repetitive tasks such as attendance tracking and resource management. It also provides real-time insights into student behavior and engagement, allowing teachers to focus on delivering high-quality education rather than administrative tasks.
              </AccordionContent>
            </AccordionItem>
            <AccordionItem value="question-14">
              <AccordionTrigger className="flex items-center justify-between bg-background rounded-md px-4 py-3 text-lg font-medium hover:bg-muted">
                <span>14. What reports does SCMS generate?</span>
              </AccordionTrigger>
              <AccordionContent className="bg-background rounded-md px-4 py-3 text-muted-foreground">
              SCMS generates detailed reports on student attendance, behavior, mood analysis, and resource usage. These reports provide valuable insights into classroom dynamics and help in making data-driven decisions for better educational outcomes.
              </AccordionContent>
            </AccordionItem>
            <AccordionItem value="question-15">
              <AccordionTrigger className="flex items-center justify-between bg-background rounded-md px-4 py-3 text-lg font-medium hover:bg-muted">
                <span>15. What are the installation requirements for SCMS?</span>
              </AccordionTrigger>
              <AccordionContent className="bg-background rounded-md px-4 py-3 text-muted-foreground">
              SCMS requires classrooms to have CCTV cameras, IoT sensors, and a stable internet connection. It can be deployed on-premises or hosted on the cloud, depending on the school’s preferences.
              These FAQs will provide clarity to users about the capabilities, implementation, and advantages of your Smart Classroom Management Software (SCMS).
              </AccordionContent>
            </AccordionItem>

          </Accordion>
        </div>
      </div>
    </section>
  </div>
  )
}

function ChevronDownIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  )
}

export default faq;
